### ISSUE TITLE
Spreadsheet and status line not shown

### ISSUE THREAD

**Issue by endelight** [corelan/EncFSGui#4] opened 2016-08-06 20:10 UTC
Hello corelan,

I like EncFSGui a lot, but there is one annoying issue: somehow the table with the created mounts are not shown. Same applies to the status bar.

This is how EncFSGui looks on my MacBook Pro with OS X 10.11.5 (15F34):

<img width="933" alt="screenshot 2016-08-06 22 06 38" src="https://cloud.githubusercontent.com/assets/10101572/17458861/1989fd4e-5c22-11e6-8a84-5f6d3cea6944.png">

Actually it should list 3 items.

Any ideas?

Cheers,
endelight

**Comment by corelanc0d3r** [comment] 2016-08-06 20:14
is the table missing every time, or just now and then ?
when you create a new mount, does it show up in the table right after creating it ?
thanks

**Comment by endelight** [comment] 2016-08-06 21:09
Wow, thanks for prompt answer 👍 

Yes, the table is missing all the time. No matter what I do. I even tried a reinstallation and also a couple of reboots... Meanwhile I figured out how to edit at least the existing entries via 

`/Users/<my_user>/Library/Preferences/encfsgui Preferences`

but it is a bit uncomfortable...

Cheers!

**Comment by corelanc0d3r** [comment] 2016-08-07 09:06
hmm not sure what is going on, it looks like these elements are just "hidden" on your box.  I'll try to forcibly set the elements to visible.  Meanwhile, can you check what happens if you choose "Hide encfsgui" and then "show encfsgui" from the OSX system icon?   Also, can you actually see your volumes listed when you click on that icon and look under "volumes" ?

**Comment by corelanc0d3r** [comment] 2016-08-07 19:48
perhaps encfsgui bails out if there is something wrong with the settings file. would you mind renaming the file to something else (so there would not be an "encfsgui Preferences" file) and see if it loads, showing the missing elements?

**Comment by corelanc0d3r** [comment] 2016-10-07 11:13
I have not been able to reproduce the issue, closing for now. Feel free to re-open if needed (and if you have performed the test mentioned above)

**Closed as completed by corelanc0d3r** 2016-10-07 11:13 UTC
